package com.otgs.customerapp

interface Constants {
    companion object {
        const val BASE_URL = "http://onthegoservices.in/api/"
        const val IMAGE_URL = "http://onthegoservices.in/"
        const val LOGIN_AUTO = "LoginAuto"
        const val REG_CUSTOMER = "regCustomer"
        const val FORGOT_PASSWORD_NEW = "ForgotPasswordNew"
        const val GET_ALL_STATES = "getAllStates"
        const val GET_CITIES = "getCities?"
        const val GET_PINCODES = "getPincodes?"
        const val RESET_PASSWORD = "resetPassword"
        const val GET_ALLYEARS = "getAllYears"
        const val GET_ALLMONTHS = "getAllMonths"
        const val SEND_OTP = "SendOTP"
        const val SUBMIT_QUERY = "submitQuery"
        const val GET_ALLFAQ = "getAllFaq"
        const val GET_ALLCATEGORIES = "getAllCategories"
        const val GET_CUSTOMERLIST = "getCustomerProfile"
        const val EDIT_CUSTOMERPROFILE = "editCustomerProfile?"
        const val GET_ALL_SERVICE_MASTERLIST = "getAllServiceMasterList"
        const val GET_SERVICE_PROVIDERLIST = "getServiceProviderList"
        const val GET_SERVICE_PROVIDERDETAILS = "getServiceProviderDetails?"
        const val GET_SOSDETAILS = "getSosDetails"
        const val GET_ALLRTORULES = "getAllRtoRules"
        const val GET_SERVICINGLIST = "getServicingList"
        const val CUSTOMER_BOOKINGDETAILS = "customerBookingDetails"
        const val GET_CUSTBRAND = "getCustBrand"
        const val ADD_CUSTOMERVEHICLE_DETAILS = "addCustomerVehicleDetails"
        const val GET_RATING_REVIEW = "getRatingReview"
        const val SUBMIT_RATING_REVIEW = "submitRatingReview"
        const val GET_ALLVEHICLETYPES = "getAllVehicleTypes"
        const val GET_VEHICLESUBTYPES = "getVehicleSubTypes?"
        const val GET_VEHICLEBRANDS = "getVehicleBrands?"
        const val GET_CUSTVEHICLELIST = "getCustVehicleList"
        const val GET_VEHICLEDETAILS = "getVehicleDetails"
        const val ABOUT_US = "aboutUs.html"


        const val KEY_TOKEN = "token"
        const val KEY_USERID = "userid"
        const val KEY_USERTYPE = "usertype"
        const val KEY_EMAIL = "email"
        const val KEY_NAME = "name"
        const val KEY_UNIQUENO = "uniqueno"
        const val IS_FIRST_ATEMPT = "is_first_atempt"
        const val KEY_MOBILE_NO = "mobile_no"
        const val KEY_PROFILE_PHOTO = "profile_photo"
    }
}