package com.otgs.customerapp.model.response

data class GarageInformationData(
    var FavStatus: String,
    var account_holder_name: String,
    var account_number: String,
    var avg_rating: Double,
    var bank_name: String,
    var branch_name: String,
    var contact_address: String,
    var contact_city: String,
    var contact_email_id: String,
    var contact_landline: String,
    var contact_landmark: String,
    var contact_location: String,
    var contact_mobile: String,
    var contact_person_name: String,
    var contact_pincode: String,
    var contact_state: String,
    var date_of_establish: String,
    var distance_from_current_location: String,
    var garage_name: String,
    var ifsc_code: String,
    var lat: String,
    var lng: String,
    var mobile_number: String,
    var owner_first_name: String,
    var owner_last_name: String,
    var photo: String,
    var pick_drop_flag: Int,
    var service_contact_number: String,
    var service_id: String,
    var sp_id: Int
)